### PR TITLE
update simple_oauth

### PR DESCRIPTION
**Pull request by cantino**

### CODE REVIEW

**Comment by cantino** [comment]
I haven't yet tried this to make sure nothing breaks in practice.  I'm testing it now.

**Comment by dsander** [comment]
I am confused, GitHub showed my a notification for the PR today. Is this still relevant?

**Comment by cantino** [comment]
No, I don't think so. But I did add you and @knu as maintainers on https://github.com/cantino/twitter-stream yesterday since @knu submitted https://github.com/cantino/twitter-stream/pull/1. Maybe GitHub did something strange with notifications?

**Comment by dsander** [comment]
Possible, thanks for adding us 😄

**Pull request closed without merging**
